FROM python:3

WORKDIR /usr/src/app

COPY submission.py .

CMD [ "python", "./submission.py" ]
# pull the base python image

#set working directory

#compile for java
#any single commands are done under RUN
#RUN javac main.java

#run executable
#to implement do CMD
# CMD ["java", "Main"]